<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<div class="container mb-5">
    <h1 class="mb-3 text-center">All Placements</h1>

    <div class="row mb-3">
        <?php foreach ($allPlacements as $placement) :
            $placementSkillIds = [
                $placement->getSkill1(),
                $placement->getSkill2(),
                $placement->getSkill3()
            ];
            $placementSkills = $skillsDataSet->fetchSkillsbyIdArray($placementSkillIds);
        ?>

        <!--  TODO pagination      -->


        <div class="card mb-2">
            <div class="card-body">
                <div class="placement-details">
                    <div class="row">
                        <div class="col-sm-4">
                            <p><strong>Company:</strong> <?= $companiesDataSet->fetchCompanyName($placement->getCompanyId()) ?></p>
                        </div>
                        <div class="col-sm-4">
                            <p><strong>Description:</strong> <?= $placement->getDescription() ?></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <p>
                                <strong>Industry:</strong> <?= $industriesDataSet->fetchIndustryNameById($placement->getIndustry()) ?>
                            </p>
                        </div>
                        <div class="col-sm-4">
                            <p><strong>Salary:</strong>
                                £<?= number_format($placement->getSalary(), 0, '.', ',') ?></p>
                        </div>
                        <div class="col-sm-4">
                            <p><strong>Location:</strong> <?= $placement->getLocation() ?></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p><strong>Start Date:</strong> <?= $placement->getStartDate() ?></p>
                        </div>
                        <div class="col-sm-4">
                            <p><strong>End Date:</strong> <?= $placement->getEndDate() ?></p>
                        </div>
                    </div>
                </div>
                <a href="#" class="btn btn-success">Apply!</a>
            </div>
            <div class="card-footer">
                <small>Skills</small>
                <?php foreach ($placementSkills as $skill) : ?>
                    <span class="badge bg-success rounded-pill text-light"><?= $skill->getSkillName() ?>(<?= $placementHelpers->getProficiencyFromSkill($skill, $allProficiencies) ?>)</span>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>


</div>

<?php require_once(base_path('views/partials/footer.phtml')) ?>