<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<div class="container mb-5">
    <form name="edit-student" action="/editprofile" method="post">
        <h1 class="mb-3 text-center">Edit your profile</h1>

        <!--first name and last name-->
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="firstName">First Name</label>
                <input type="text" class="form-control" name="firstName" id="firstName" value="<?= $user->getFirstName() ?>">
            </div>
            <div class="col-md-6 ">
                <label class="mb-2" for="lastName">Last Name</label>
                <input type="text" class="form-control" name="lastName" id="lastName" value="<?= $user->getLastName() ?>">
            </div>
        </div>

        <!--email and location-->
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="email">Email</label>
                <input type="text" class="form-control" name="email" id="email" value="<?= $user->getEmail() ?>">
            </div>
            <div class="col-md-6 ">
                <label class="mb-2" for="location">Location</label>
                <input type="text" class="form-control" name="location" id="location" value="<?= $userStudentData->getLocation() ?>">
            </div>
        </div>

        <!--contact number and location-->
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="contactNumber">Contact Number</label>
                <input type="text" class="form-control" name="contactNumber" id="contactNumber" value="<?= $user->getPhoneNumber() ?>">
            </div>
        </div>

        <!--course and institution-->
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="course">Course</label>
                <select class="form-select" name="course" id="course">
                    <option value="<?= $userCourse->getCourseName() ?>"><?= $userCourse->getCourseName() ?></option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="institution">Institution</label>
                <select class="form-select" name="institution" id="institution">
                    <option value="<?= $userStudentData->getInstitution() ?>"><?= $userStudentData->getInstitution() ?></option>
                </select>
            </div>
        </div>

        <!--skill 1 and proficiency-->
        <div class="row mb-2">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="skill1">Skill 1</label>
                <select class="form-select" name="skill1" id="skill1">
                    <option value="<?= $userSkills[0]->getSkillName() ?>"><?= $userSkills[0]->getSkillName() ?></option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="proficiency1">Proficiency</label>
                <select class="form-select" name="proficiency1" id="proficiency1">
                    <option value="<?= $userSkillsAndProficiencies[0]['proficiency']->getProficiency() ?>"><?=$userSkillsAndProficiencies[0]['proficiency']->getProficiency()?></option>
                </select>
            </div>
        </div>

        <!--skill 2 and proficiency-->
        <div class="row mb-2">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="skill2">Skill 2</label>
                <select class="form-select" name="skill2" id="skill2">
                    <option value="<?= $userSkills[1]->getSkillName() ?>"><?= $userSkills[1]->getSkillName() ?></option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="proficiency2">Proficiency</label>
                <select class="form-select" name="proficiency2" id="proficiency2">
                    <option value="<?= $userSkillsAndProficiencies[1]['proficiency']->getProficiency() ?>"><?=$userSkillsAndProficiencies[1]['proficiency']->getProficiency()?></option>
                </select>
            </div>
        </div>

        <!--skill 3 and proficiency-->
        <div class="row justify-content-center mb-2">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="skill3">Skill 3</label>
                <select class="form-select" name="skill3" id="skill3">
                    <option value="<?= $userSkills[2]->getSkillName() ?>"><?= $userSkills[2]->getSkillName() ?></option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="proficiency3">Proficiency</label>
                <select class="form-select" name="proficiency3" id="proficiency3">
                    <option value="<?= $userSkillsAndProficiencies[2]['proficiency']->getProficiency() ?>"><?=$userSkillsAndProficiencies[2]['proficiency']->getProficiency()?></option>
                </select>
            </div>
        </div>

        <!--submit button-->
        <div class="row justify-content-center mb-2">
            <div class="col-md-3 text-center ">
                <button class="btn btn-success btn-lg btn-block dark-green-bg" id="submit" name="submit" value="first" type="submit">Save Changes    <i class="bi bi-arrow-right"></i></button>
            </div>
        </div>

    </form>
</div>

<?php require_once(base_path('views/partials/footer.phtml')) ?>