<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-...." crossorigin="anonymous"/>

<footer id="footer" class="footer ">
    <!-- Footer Top -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer">
                        <h2>About Us</h2>
                        <p>We're over 70,000 members in 150 countries, and a wider community of business leaders, educators, practitioners and policy-makers all committed to our mission.

                            As a charity with a royal charter, our agenda is to lead the IT industry through its ethical challenges, to support the people who work in the industry, and to make IT good for society.</p>
                        <!-- Social -->
                        <ul style="list-style: none; color:white; padding: 0;" class="social">
                            <li><a href="#"><i class="social-icon fab fa-facebook"></i></a></li>
                            <li><a href="#"><i class="icofont-google-plus"></i></a></li>
                            <li><a href="#"><i class="icofont-twitter"></i></a></li>
                            <li><a href="#"><i class="icofont-vimeo"></i></a></li>
                            <li><a href="#"><i class="icofont-pinterest"></i></a></li>
                        </ul>
                        <!-- End Social -->
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer f-link">
                        <h2>Quick Links</h2>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12">
                                <ul>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Services</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Our Cases</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Other Links</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer">
                        <h2>Details</h2>
                        <p>Our program connects talented students with outstanding placement programs, seamlessly
                            pairing employers with their ideal candidates. It's a mutually advantageous platform,
                            streamlining the process for both students seeking opportunities and employers searching for
                            top-tier talent..</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer">
                        <h2>Newsletter</h2>
                        <p>Subscribe to our newsletter to get all our news in your inbox</p>
                        <form action="mail/mail.php" method="get" target="_blank" class="newsletter-inner">
                            <input name="email" placeholder="Email Address" class="common-input"
                                   onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Your email address'" required="" type="email">
                            <button class="button"><img style="width:20px;height:20px;"
                                                        src="https://abrfashion.com/demo/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Footer Top -->
    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-12 text-left">
                    <div class="copyright-content">
                        <p>@ 2023, University of Salford, group 17 HackCamp project'</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12 text-center">
                    <div class="copyright-content">
                        <ul style="list-style: none; color:white; padding: 0;">
                            <li style="display: inline;">Data Privacy Notice</li>
                            <li style="display: inline;padding-left: 10;">Copyright Notice</li>
                            <li style="display: inline;padding-left: 10;">Use Of Cookies</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12 text-right">
                    <div class="copyright-content">
                        <ul style="list-style: none; color:white; padding: 0;" class="social-icons">
                            <li style="display: inline;font-size: 24px;"><a href="#" class="social-icon"><i
                                            class="fab fa-facebook"></i></a></li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#"
                                                                                             class="social-icon"><i
                                            class="fab fa-twitter"></i></a></li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#"
                                                                                             class="social-icon"><i
                                            class="fab fa-instagram"></i></a></li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#"
                                                                                             class="social-icon"><i
                                            class="fab fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Copyright -->
</footer>