<!-- Required dependencies for Bootstrap JS -->
<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-oZNvZROlRSU8Lwz+w/mAJPIa4LCAIXizBr6S/Jc5Xa9aQb5T6NPZCIa7K7ON5tc9" crossorigin="anonymous"></script>
<footer id="footer" class="footer ">
    <!-- Footer Top -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer">
                        <h2>About Us</h2>
                        <p>We're over 70,000 members in 150 countries, and a wider community of business leaders, educators, practitioners and policy-makers all committed to our mission.

                            As a charity with a royal charter, our agenda is to lead the IT industry through its ethical challenges, to support the people who work in the industry, and to make IT good for society.</p>
                        <!-- Social -->
                        <!--                        <ul style="list-style: none; color:white; padding: 0;" class="social">-->
                        <!--                            <li><a href="#" class="fa-brands fa-facebook"></a></li>-->
                        <!--                            <li><a href="#" class="fa-brands fa-instagram"></a></li>-->
                        <!--                            <li><a href="#" class="fa-brands fa-twitter"></a></li>-->
                        <!--                            <li><a href="#" class="fa-brands fa-linkedin"></a></li>-->
                        <!--                            <li><a href="#" class="fa-brands fa-youtube"></a></li>-->
                        <!--                        </ul>-->
                        <!-- End Social -->
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer f-link">
                        <h2>Quick Links</h2>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12">
                                <ul>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Services</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Our Cases</a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Other Links</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <div class="single-footer">
                        <h2>Details</h2>
                        <p>Our program connects talented students with outstanding placement programs, seamlessly
                            pairing employers with their ideal candidates. It's a mutually advantageous platform,
                            streamlining the process for both students seeking opportunities and employers searching for
                            top-tier talent.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Footer Top -->
    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-12 text-left">
                    <div class="copyright-content">
                        <p>@ 2023, University of Salford, group 17 HackCamp project</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12 text-center">
                    <div class="copyright-content">
                        <ul style="list-style: none; color:white; padding: 0;">
                            <li style="display: inline;">Data Privacy Notice</li>
                            <li style="display: inline;padding-left: 10;">Copyright Notice</li>
                            <li style="display: inline;padding-left: 10;">Use Of Cookies</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12 text-right">
                    <div class="copyright-content">
                        <ul style="list-style: none; color:white; padding: 0;" class="social-icons">
                            <li style="display: inline;font-size: 24px;">
                                <a href="#" class="social-icon"><i class="fab fa-facebook"></i></a>
                            </li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;">
                                <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
                            </li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;">
                                <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                            </li>
                            <li style="display: inline;padding-left: 15;font-size: 24px;">
                                <a href="#" class="social-icon"><i class="fab fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Copyright -->
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>