<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-...." crossorigin="anonymous" />

<footer id="footer" class="footer ">
			<!-- Footer Top -->
			<div class="footer-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>About Us</h2>
								<p>Lorem ipsum dolor sit am consectetur adipisicing elit do eiusmod tempor incididunt ut labore dolore magna.</p>
								<!-- Social -->
								<ul class="social">
									<li><a href="#"><i class="icofont-facebook"></i></a></li>
									<li><a href="#"><i class="icofont-google-plus"></i></a></li>
									<li><a href="#"><i class="icofont-twitter"></i></a></li>
									<li><a href="#"><i class="icofont-vimeo"></i></a></li>
									<li><a href="#"><i class="icofont-pinterest"></i></a></li>
								</ul>
								<!-- End Social -->
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer f-link">
								<h2>Quick Links</h2>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12">
										<ul>
											<li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
											<li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a></li>
											<li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Services</a></li>
											<li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Our Cases</a></li>
											<li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>Other Links</a></li>	
										</ul>
									</div>
									
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Details</h2>
								<p>Lorem ipsum dolor sit ame consectetur adipisicing elit do eiusmod tempor incididunt.</p>
								
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Newsletter</h2>
								<p>subscribe to our newsletter to get allour news in your inbox.. Lorem ipsum dolor sit amet, consectetur adipisicing elit,</p>
								<form action="mail/mail.php" method="get" target="_blank" class="newsletter-inner">
									<input name="email" placeholder="Email Address" class="common-input" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Your email address'" required="" type="email">
									<button class="button"><i class="icofont icofont-paper-plane"></i></button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Footer Top -->
			<!-- Copyright -->
			<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-12 text-left">
                <div class="copyright-content">
                    <p>@ 2023, University of Salford, group 17 HackCamp project'</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12 text-center">
    <div class="copyright-content">
        <ul style="list-style: none; color:white; padding: 0;">
            <li  style="display: inline;">Data Privacy Notice</li>
            <li style="display: inline;padding-left: 10;">Copyright Notice</li>
            <li style="display: inline;padding-left: 10;">Use Of Cookies</li>
        </ul>
    </div>
</div>
<div class="col-lg-4 col-md-4 col-12 text-right">
    <div class="copyright-content">
        <ul style="list-style: none; color:white; padding: 0;" class="social-icons">
            <li style="display: inline;font-size: 24px;"><a href="#" class="social-icon"><i class="fab fa-facebook"></i></a></li>
            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#" class="social-icon"><i class="fab fa-twitter"></i></a></li>
            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#" class="social-icon"><i class="fab fa-instagram"></i></a></li>
            <li style="display: inline;padding-left: 15;font-size: 24px;"><a href="#" class="social-icon"><i class="fab fa-linkedin"></i></a></li>
        </ul>
    </div>
</div>
        </div>
    </div>
</div>
			<!--/ End Copyright -->
		</footer>