<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Home - <?= $pageTitle; ?></title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="/CSS/hackcampCSS.css"> 
    <link rel="stylesheet" href="https://abrfashion.com/demo/style.css">
	<link rel="stylesheet" href="https://abrfashion.com/demo/bootstrap.min.css">
    
    <link rel="stylesheet" href="https://abrfashion.com/demo/responsive.css">
    <link rel="stylesheet" href="https://abrfashion.com/demo/bootstrap.min.css">
    <link rel="stylesheet" href="https://abrfashion.com/demo/slicknav.min.css">
    <link rel="stylesheet" href="https://abrfashion.com/demo/nice-select.css">
    <!-- <link rel="stylesheet" href="https://abrfashion.com/demo/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-JN6bX+59QC72+DJSaaFO6xiJ5YK8XD1b+jyyB4+MjVQMdBz2aArZP4T5fxO/7ZkexqpYRYJDc1eDHQ+r5H/5ZcA==" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://abrfashion.com/demo/normalize.css">
    <link rel="stylesheet" href="https://abrfashion.com/demo/icofont.css">
    <script src="https://abrfashion.com/demo/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-sTQR4/BIMBy7GGNjkXt87rvlOKDP4c6d7La5n3SkXjFy1eMz8lDOc/g9DQDvDBDT" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" rel="stylesheet">

<!-- Required dependencies for Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-oZNvZROlRSU8Lwz+w/mAJPIa4LCAIXizBr6S/Jc5Xa9aQb5T6NPZCIa7K7ON5tc9" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-sTQR4/BIMBy7GGNjkXt87rvlOKDP4c6d7La5n3SkXjFy1eMz8lDOc/g9DQDvDBDT" crossorigin="anonymous"></script>


</head>



 