<header class="header mb-5">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 col-12">
                    <div class="logo">
                        <a href="/dashboard"><img class="img-fluid mx-auto" style="max-width: 30%;" src="bcs-logo.svg" alt="#"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <!-- Top Contact -->
                    <ul class="top-contact">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Making IT good for society</a></li>
                        <li><a href="#">About Placements</a></li>
                        <li><a href="#">Our Team</a></li>
                        <?php if (!$_SESSION['user']['loggedIn']) : ?>
                            <li>
                                <a class="btn btn-success" href="/login">Login to MyBCS</a>
                            </li>
                        <?php else : ?>
                            <li>
                                <a class="btn btn-success" href="/signout">Sign out</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <!-- End Top Contact -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->

    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="inner">
                <div class="row">
                    <div class="col-lg-1 col-md-3 col-12">
                        <!-- End Logo -->
                        <!-- Mobile Nav -->
                        <div class="mobile-nav">

                        </div>
                        <!-- End Mobile Nav -->
                    </div>
                    <div class="col-lg-10 col-md-9 col-12">
                        <!-- Main Menu -->
                        <div class="main-menu">
                            <nav class="navigation">
                                <ul class="nav menu">
                                    <li><a href="#">Membership & registrations</a>

                                    </li>
                                    <li><a href="#">IT careers </a></li>
                                    <li><a href="#">Qualifications & certifications </a></li>
                                    <li><a href="#">Event & awards</a>
                                        <ul class="dropdown">
                                            <li><a href="404.html">404 Error</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">opinion & research</a>
                                        <ul class="dropdown">
                                            <li><a href="blog-single.html">Blog Details</a></li>
                                        </ul>
                                    </li>

                                </ul>
                            </nav>
                        </div>
                        <!--/ End Main Menu -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>