<header class="header">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-7 col-12">
                    <div class="logo">
                        <a href="/"><img class="img-fluid mx-auto" style="max-width: 30%;" src="bcs-logo.svg"
                                         alt="#"></a>
                    </div>

                    <!-- Top Contact -->
                    <ul class="top-contact">
                        <li><a href="https://www.bcs.org/about-us">About us</a></li>
                        <li><a href="http://impact.bcs.org">Making IT good for society</a></li>
                        <li><a href="/team">Our Team</a></li>
                        <li>|</li>
                        <li><a href="/">Home</a></li>
                        <?php if (authenticated()) : ?>
                            <li><a href="/dashboard">Dashboard</a></li>
                            <?php if ($_SESSION['user']['usertype'] == 1) : ?>
                                <li><a href="/placements">All Placements</a></li>
                            <?php elseif ($_SESSION['user']['usertype'] == 2) : ?>
                                <li><a href="/students">All Students</a></li>
                            <?php endif; ?>
                            <li><a href="/editprofile">Edit Profile</a></li>

                            <li class="nav-item btn">
                                <a class="nav-link login-button" href="/signout">Sign out</a>
                            </li>
                        <?php elseif (!authenticated()) : ?>
                            <li class="nav-item btn">
                                <a class="nav-link login-button" href="/login">Login to MyBCS</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <!-- End Top Contact -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="inner">
                <div class="row">
                    <div class="col-lg-10 col-md-9 col-12">
                        <!-- Main Menu -->
                        <div class="main-menu">
                            <nav class="navigation">
                                <ul class="nav menu">
                                    <li><a href="https://www.bcs.org/membership-and-registrations/">Membership &
                                            Registrations</a></li>
                                    <li><a href="https://www.bcs.org/it-careers/">IT Careers </a></li>
                                    <li><a href="https://www.bcs.org/qualifications-and-certifications">Qualifications &
                                            Certifications </a></li>
                                    <li><a href="https://www.bcs.org/events/awards-and-competitions/">Event & Awards</a>
                                    </li>
                                    <li><a href="https://www.bcs.org/articles-opinion-and-research/">Opinion &
                                            Research</a></li>
                                </ul>
                            </nav>
                        </div>
                        <!--/ End Main Menu -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="containers">
        <div class="row ">
            <!-- Mobile Nav -->
            <div class="col-12 col-sm-3 col-md-4 em">
                <div class="mobile-nav">
                    <button class="navbar-toggler tgl" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                        <i class="fa-solid fa-bars"></i>
                    </button>

                    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample"
                         aria-labelledby="offcanvasExampleLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h5>
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                                    aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <ul class="navbar-nav justify-content-end flex-grew-1 pe-3">
                                <li><a href="https://www.bcs.org/membership-and-registrations/">Membership &
                                        Registrations</a></li>
                                <li><a href="https://www.bcs.org/it-careers/">IT Careers </a></li>
                                <li><a href="https://www.bcs.org/qualifications-and-certifications">Qualifications &
                                        Certifications </a></li>
                                <li><a href="https://www.bcs.org/events/awards-and-competitions/">Event & Awards</a>
                                </li>
                                <li><a href="https://www.bcs.org/articles-opinion-and-research/">Opinion & Research</a>
                                </li>

                                <li><a href="https://www.bcs.org/about-us">About us</a></li>
                                <li><a href="http://impact.bcs.org">Making IT good for society</a></li>
                                <li><a href="/team">Our Team</a></li>
                                <?php if (authenticated()) : ?>
                                    <li><a href="/dashboard">Dashboard</a></li>
                                    <?php if ($_SESSION['user']['usertype'] == 1) : ?>
                                        <li><a href="/placements">All Placements</a></li>
                                    <?php elseif ($_SESSION['user']['usertype'] == 2) : ?>
                                        <li><a href="/students">All Students</a></li>
                                    <?php endif; ?>
                                    <?php if (!$_SESSION['user']['loggedIn']) : ?>
                                        <li class="nav-item btn">
                                            <a class="nav-link login-button" href="/login">Login to MyBCS</a>
                                        </li>
                                    <?php else : ?>
                                        <li><a href="/editprofile">Edit Profile</a></li>

                                        <li class="nav-item btn">
                                            <a class="nav-link login-button" href="/signout">Sign out</a>
                                        </li>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Logo -->
            <div class="col-12 col-sm-3 col-md-4 m lg-f">
                <div class="logo">
                    <a href="/"><img class="logo-mb" src="bcs-logo.svg"
                                     alt="#"></a>
                </div>
            </div>
        </div>
    </div>
</header>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>