<?php ?>

<div class="dropdown">
    <button class="btn dropdown-toggle" type="button" id="dropdown1" data-bs-toggle="dropdown">
        Membership & registrations
    </button>

    <ul class="dropdown-menu" aria-labelledby="dropdown1">
        <li><a class="dropdown-item" href="">Become a member</a></li>
        <li><a class="dropdown-item" href="">Member communities</a></li>
        <li><a class="dropdown-item" href="">Get registered</a></li>
        <li><a class="dropdown-item" href="">Membership for organisations</a></li>
        <li><a class="dropdown-item" href="">Academic membership</a></li>
        <li><a class="dropdown-item" href="">Register of BCS members</a></li>
        <li><a class="dropdown-item" href="">Our members</a></li>
    </ul>

</div>