<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<?php
$user = $usersDataSet->fetchUserById($_SESSION['user']['id']);
$matches = $placementHelpers->getStudentMatchesForCompany($user->getCompanyId(), $allStudents);

?>

    <script>
        // button toggle code, let me know if i should move this to a separate file
        $(document).ready(function() {
            $('.show-more-button').on('click', function() {
                const placementId = $(this).data('placement');
                $(`.placement-${placementId}`).slideDown(); // Show all cards for the specific placement
                $(this).hide(); // Hide the show more button
                $(`.collapse-button[data-placement=${placementId}]`).show(); // Show the collapse button
            });

            $('.collapse-button').on('click', function() {
                const placementId = $(this).data('placement');
                $(`.placement-${placementId}`).slideToggle(); // Toggle visibility of cards for the specific placement
                $(this).hide(); // Hide the collapse button
                $(`.show-more-button[data-placement=${placementId}]`).show(); // Show the show more button
            });
        });
    </script>

    <div class="container">

        <h1>Student Matches</h1>
        <p>Based on the placements you have posted, the following students have been identified as potential
            matches.</p>

        <?php if (!empty($errors)) : ?>
            <ul class="error-list list-unstyled text-center mx-6 mb-3 mb-lg-4">
                <?php foreach ($errors as $error) : ?>
                    <strong><li class="text-danger mt-2 list"><?= $error ?></li></strong>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $companyName = $companiesDataSet->fetchCompanyName($user->getCompanyId()) ?>

        <div class="container mt-5">
            <?php if (empty($matches)) : ?>
                <h3 class="mb-3">You don't have any placements!</h3>
            <?php else : ?>

            <?php foreach ($matches as $placementId => $placementMatches) : ?>
                <div class="row">
                    <div class="card col-md-12 mb-3">

                        <div class="placement-details">
                            <div class="row">
                                <div class="col-sm-4">
                                    <p>
                                        <strong>Company:</strong> <?= $companyName ?>
                                    </p>
                                </div>
                                <div class="col-sm-4">
                                    <p>
                                        <strong>Description:</strong> <?= $placementMatches['placement']->getDescription() ?>
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-4">
                                    <p>
                                        <strong>Industry:</strong> <?= $industriesDataSet->fetchIndustryNameById($placementMatches['placement']->getIndustry()) ?>
                                    </p>
                                </div>
                                <div class="col-sm-4">
                                    <p><strong>Salary:</strong>
                                        £<?= number_format($placementMatches['placement']->getSalary(), 0, '.', ',') ?>
                                    </p>
                                </div>
                                <div class="col-sm-4">
                                    <p><strong>Location:</strong> <?= $placementMatches['placement']->getLocation() ?>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <p><strong>Start
                                            Date:</strong> <?= $placementMatches['placement']->getStartDate() ?></p>
                                </div>
                                <div class="col-sm-4">
                                    <p><strong>End Date:</strong> <?= $placementMatches['placement']->getEndDate() ?>
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <form action="/dashboard" method="post">
                                <div class="col-sm-4">
                                    <input type="hidden" name="placementId" value="<?= $placementId ?>">
                                    <button class="btn btn-danger" style="background-color: #dc3545" id="delete" name="delete" value="delete" type="submit">
                                        <strong>Delete</strong>
                                    </button>
                                </div>
                                </form>
                            </div>
                        </div>

                        <!-- Display matched students for this placement with their grades -->
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Matched Students:</h4>
                                <div class="row">
                                    <?php
                                    $cardCounter = 0;

                                    $placementMatches['students'] = array_reverse($placementMatches['students']); // reverse the array so the highest grade is first

                                    foreach ($placementMatches['students'] as $studentId => $studentData) :
                                            $user = $usersDataSet->fetchUserByStudentId($studentId);
                                            if ($user == null)
                                                continue; // skip this student if they don't exist
                                            $studentCourse = $coursesDataSet->fetchCourseById($studentData['studentData']->getCourse()); // course of the student
                                            $prefIndustry = $industriesDataSet->fetchIndustryNameById($studentData['studentData']->getPrefIndustry()); // preferred industry of the student
                                            $cardCounter++;

                                            $moreThanFourStudents = $cardCounter > 4 ? "placement-{$placementId}" : ""; // if there are more than 4 students, add the placement id to the class name

                                            ?>
                                        <div class="card col-md-6 mb-2 <?= $moreThanFourStudents ?>" style="<?= $cardCounter > 4 ? "display:none;" : "display:block;" ?>">
                                            <p>
                                                <strong>Student Name:</strong> <?= $user->getFirstName() ?> <?= $user->getLastName() ?>
                                                <br>
                                                <strong>Student Course:</strong> <?= $studentCourse->getCourseName() ?>
                                                <br>
                                                <strong>Student Institution:</strong> <?= $studentData['studentData']->getInstitution() ?>
                                                <br>
                                                <strong>Student Preferred Industry:</strong> <?= $prefIndustry ?><br>
                                                <strong>Student Location:</strong> <?= $studentData['studentData']->getLocation() ?>
                                                <br>
                                                <a href="mailto:<?= $usersDataSet->fetchEmailById($studentId) ?>?subject=&amp;body=" target="_blank" class="btn btn-success float-end mb-2">Contact</a>
                                                <span class="badge rounded-pill text-dark mb-3" style="background-color:#bccf00; border-color: #bccf00">(Compatibility: <?= $studentData['grade'] ?>)</span>
                                            </p>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <div class="row justify-content-center">
                                    <?php $displayStyle = $cardCounter > 4 ? "display:block;" : "display:none;" // used to display the display tag, if less than 4 students then don't display button ?>
                                    <?php if ($cardCounter > 4) : ?>
                                        <div class="col-md-auto">
                                            <button class="btn btn-success mb-2 show-more-button" data-placement="<?= $placementId ?>" style="<? $displayStyle ?>">
                                                Show More
                                            </button>
                                        </div>
                                        <div class="col-md-auto">
                                            <button class="btn btn-success mb-2 collapse-button" data-placement="<?= $placementId ?>" style="display:none;">
                                                Collapse
                                            </button>
                                        </div>
                                    <?php else: ?>
                                    <div class="col-md-auto">
                                        <button class="btn btn-success mb-2 show-more-button" data-placement="<?= $placementId ?>" style="<?= $displayStyle ?>">
                                            Show More
                                        </button>
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <?php endforeach; ?>

            <?php endif; ?>
        </div>

    </div>


<?php require_once(base_path('views/partials/footer.phtml')) ?>