<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

    <div class="container">
        <?php
        if ($testStudent == null) {
            echo "<h1>Matches not found</h1>";
            exit();
        }

        $skillNames = $placementHelpers->getSkillNames($testStudent, $allSkills, $allProficiencies);
        $placementMatches = $placementHelpers->getPlacementMatches($testStudent, $allPlacements, $allProficiencies, $allSkills);
        $studentSkills = [
            $testStudent->getSkill1(),
            $testStudent->getSkill2(),
            $testStudent->getSkill3()
        ];
        ?>

        <h1>Placement Matches</h1>
        <p>Based on your Skills:
            <?php foreach ($skillNames as $skillId => $skillData) : ?>
                <span class="badge rounded-pill text-dark" style="background-color:#bccf00; border-color: #bccf00">
                    <?= $skillData['skillName'] ?> (<?= $skillData['skillProficiency'] ?>)
                </span>
            <?php endforeach; ?>
            We have determined these Placements for you!
        </p>


        <div class="container">
            <div class="placement-matches">
                <?php foreach ($placementMatches as $matchType => $placements): ?>
                    <?php if (!empty($placements)): ?>
                        <h3><?= ucfirst($matchType) ?> Matches</h3>
                        <div class="match-type">
                            <?php foreach ($placements as $placement): ?>
                                <div class="card border-<?php
                                echo ($matchType === 'excellent') ? 'success' :
                                    (($matchType === 'good') ? 'warning' : 'danger');
                                ?> mb-3">
                                    <!-- Display placement details -->
                                    <div class="card-body">
                                        <div class="placement-details">
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p><strong>Company:</strong> <?= $companiesDataSet->fetchCompanyName($placement->getCompanyId()) ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Description:</strong> <?= $placement->getDescription() ?></p>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p>
                                                        <strong>Industry:</strong> <?= $industriesDataSet->fetchIndustryNameById($placement->getIndustry()) ?>
                                                    </p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Salary:</strong>
                                                        £<?= number_format($placement->getSalary(), 0, '.', ',') ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Location:</strong> <?= $placement->getLocation() ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p><strong>Start Date:</strong> <?= $placement->getStartDate() ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>End Date:</strong> <?= $placement->getEndDate() ?></p>
                                                </div>
                                            </div>
                                        </div>
                                        <a href="#" class="btn btn-success">Apply!</a>
                                    </div>

                                    <div class="card-footer">
                                        <small>Matched Skills:</small>
                                        <?php
                                        $userSkills = [
                                            $testStudent->getSkill1(),
                                            $testStudent->getSkill2(),
                                            $testStudent->getSkill3()
                                        ];

                                        $placementSkills = [
                                            $placement->getSkill1(),
                                            $placement->getSkill2(),
                                            $placement->getSkill3()
                                        ];
                                        ?>
                                        <?php foreach ($placementSkills as $skillId): ?>
                                            <?php foreach ($allSkills as $skill): ?>
                                                <?php if ($skill->getId() === $skillId && in_array($skillId, $userSkills)): ?>
                                                    <span class="badge rounded-pill text-dark" style="background-color:#bccf00; border-color: #bccf00"><?= $skill->getSkillName() ?> (<?= $placementHelpers->getProficiencyFromSkill($skill, $allProficiencies) ?>)</span>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>

    </div>


<?php require_once(base_path('views/partials/footer.phtml')) ?>