<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

    <div class="container">
        <?php
        if ($testStudent == null) {
            echo "<h1>Matches not found</h1>";
            exit();
        }

        $skillNames = $placementHelpers->getSkillNames($testStudent, $allSkills, $allProficiencies);
        $placementMatches = $placementHelpers->getPlacementMatchesNew($testStudent, $allPlacements, $allSkills);
        $studentSkills = [
            $testStudent->getSkill1(),
            $testStudent->getSkill2(),
            $testStudent->getSkill3()
        ];
        ?>

        <h1>Placement Matches</h1>
        <?php if (sizeof($placementMatches, 1) == 3): // check if only the criteria are in array and no other data ('excellent', 'good', 'poor')?>
            <div class="row mb-2">
                <div class="mx-auto mb-2 text-center border">
                    <h2 class="mb-2">No Placements Found 😥</h2>
                </div>
            </div>
        <?php else: ?>

        <p>Based on your Skills:
            <?php foreach ($skillNames as $placementSkillId => $skillData) : ?>
                <span class="badge rounded-pill text-dark" style="background-color:#bccf00; border-color: #bccf00">
                    <?= $skillData['skillName'] ?> (<?= $skillData['skillProficiency'] ?>)
                </span>
            <?php endforeach; ?>
            We have determined these Placements for you!
        </p>

        <div class="container">
            <div class="placement-matches">
                <?php foreach ($placementMatches as $matchType => $placements): ?>
                    <?php if (!empty($placements)): ?>
                        <h3><?= ucfirst($matchType) ?> Matches</h3>
                        <div class="match-type">
                            <?php foreach ($placements as $placement): ?>
                                <?php $borderColour = ($matchType === 'excellent') ? 'success' :
                                    (($matchType === 'good') ? 'warning' : 'danger'); // this is for the border colour of the card ?>

                                <div class="card border-<?= $borderColour?> mb-3">
                                    <!-- Display placement details -->
                                    <div class="card-body">
                                        <div class="placement-details">
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p><strong>Company:</strong> <?= $companiesDataSet->fetchCompanyName($placement->getCompanyId()) ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Description:</strong> <?= $placement->getDescription() ?></p>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p>
                                                        <strong>Industry:</strong> <?= $industriesDataSet->fetchIndustryNameById($placement->getIndustry()) ?>
                                                    </p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Salary:</strong>
                                                        £<?= number_format($placement->getSalary(), 0, '.', ',') ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>Location:</strong> <?= $placement->getLocation() ?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <p><strong>Start Date:</strong> <?= $placement->getStartDate() ?></p>
                                                </div>
                                                <div class="col-sm-4">
                                                    <p><strong>End Date:</strong> <?= $placement->getEndDate() ?></p>
                                                </div>
                                            </div>
                                        </div>
                                        <a href="mailto:<?= $companiesDataSet->fetchCompanyEmail($placement->getCompanyId()) ?>?subject=BCS%20Placement%20Finder%20Applicant&amp;body=Name%3A%20%0D%0AContact%20Number%3A%20%0D%0ALocation%3A%20%0D%0ACourse%3A%20%0D%0AInstitution%3A%20%0D%0APreferred%20Industry%3A%20%0D%0ASkills%20-%20Proficiencies%3A%20%0D%0A%0ACV%20is%20attached (attach CV)%20" target="_blank" class="btn btn-success text-dark">Apply!</a>
                                    </div>

                                    <div class="card-footer">
                                        <small>Matched Skills:</small>
                                        <?php
                                        $userSkills = [
                                            $testStudent->getSkill1(),
                                            $testStudent->getSkill2(),
                                            $testStudent->getSkill3()
                                        ];
                                        $placementSkills = [
                                            $placement->getSkill1(),
                                            $placement->getSkill2(),
                                            $placement->getSkill3()
                                        ]; ?>

                                        <?php foreach ($placementSkills as $placementSkillId): // loop through placement skill ids ?>
                                            <?php foreach ($allSkills as $skill): // loop through all skills
                                                // if skill id and placement skill id match, and the placement skill id in the user skills then display ?>
                                                <?php if ($skill->getId() === $placementSkillId && in_array($placementSkillId, $userSkills)): ?>
                                                    <span class="badge rounded-pill text-dark"
                                                          style="background-color:#bccf00; border-color: #bccf00">
                                                        <?= $skill->getSkillName() ?> (<?= $placementHelpers->getProficiencyFromSkill($skill, $allProficiencies) ?>)
                                                    </span>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>

        <?php endif; ?>
    </div>


<?php require_once(base_path('views/partials/footer.phtml')) ?>