<?php require_once(base_path('views/partials/head.phtml')) ?>

<div id="main-content">
    <section class="vh-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-15">
                    <div class="card text-black border-0">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-15 order-2 order-lg-1">
                                    <div class="text-center">
                                        <img src="https://sts.bcs.org/bcs-logo.svg" alt="Image not found!" class="img-fluid mb-4" style="max-width: 15%;" />
                                        <p class="h5 fw-bold mx-4 mb-3 mb-lg-4">Log in using your email address and password</p>
                                    </div>

                                    <form class="mx-1 mx-md-4" action="/login" method="POST">
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="text" id="email" name="email" placeholder="Email address" class="form-control <?= !empty($errors) ? 'has-error' : '' ?>" required>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" id="password" name="password" placeholder="Password" class="form-control <?= !empty($errors) ? 'has-error' : '' ?>" required>
                                            </div>
                                        </div>
                                        <?php if (!empty($errors)) : ?>
                                            <ul class="error-list list-unstyled d-flex justify-content-center mx-6 mb-3 mb-lg-4">
                                                <?php foreach ($errors as $error) : ?>
                                                    <strong><li class="text-danger mt-2 list"><?= $error ?></li></strong>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>

                                        <div class="d-flex justify-content-center mx-6 mb-3 mb-lg-4">
                                            <button class="btn btn-success btn-lg btn-block" type="submit">Login <i class="bi bi-arrow-right"></i></button>
                                        </div>

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <a href="/register" class="underline text-success">Don't Have an Account? Register Here!</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
