<?php require base_path('views/partials/head.phtml') ?>

<div class="container mb-5">
    <form name="register1" action="/register" method="post">
        <div class="row">
            <div class="col-md-4">
                <img src="https://sts.bcs.org/bcs-logo.svg" alt="Image not found!" class="img-fluid mx-auto mb-4"
                     style="max-width: 25%;"/>
            </div>
            <div class="col-md-4">
                <h1 class="mb-3 text-center">Create your BCS account</h1>
                <u><p class="text-center mb-4 text-success"><a href="/login">Already have an account? Log in</a></p></u>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label class="mb-2" for="firstName">*First Name</label>
                <input type="text" class="form-control <?= !empty($errors['InvalidName']) ? 'has-error' : '' ?>"
                       name="firstName" id="firstName" required>
            </div>
            <div class="col-md-6 ">
                <label class="mb-2" for="lastName">*Last Name</label>
                <input type="text" class="form-control <?= !empty($errors['InvalidLastName']) ? 'has-error' : '' ?>"
                       name="lastName" id="lastName" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label class="mb-2" for="accountType">*Account Type</label>
                <select class="form-select" name="accountType" id="accountType">
                    <option value="" selected disabled>Select Your User Type</option>
                    <option value="student">Student</option>
                    <option value="employer">Employer</option>
                    <option value="CareersWorker">University Careers Office Staff</option>
                    <option value="LibraryUser">University Library User</option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="email">*Email</label>
                <input type="text" class="form-control <?= !empty($errors['InvalidEmail']) ? 'has-error' : '' ?>"
                       name="email" id="email" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label class="mb-2" for="password">*Password</label>
                <input type="text" class="form-control <?= !empty($errors['InvalidPassword']) ? 'has-error' : '' ?>"
                       name="password" id="password" required>
            </div>
            <div class="col-md-6">
                <label class="mb-2" for="confirmPassword">*Confirm Password</label>
                <input type="text" class="form-control <?= !empty($errors['PasswordMatch']) ? 'has-error' : '' ?>"
                       name="confirmPassword" id="confirmPassword" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <label class="mb-2" for="contactNumber">*Contact Phone Number</label>
                <input type="text" class="form-control" name="contactNumber" id="contactNumber">
            </div>
        </div>


        <?php if (!empty($errors)) : ?>
            <ul class="error-list list-unstyled text-center mx-6 mb-3 mb-lg-4">
                <?php foreach ($errors as $error) : ?>
                    <strong>
                        <li class="text-danger mt-2 list"><?= $error ?></li>
                    </strong>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <h6 class="mb-3 text-center">How we use your data</h6>
        <p>We’ll store your basic personal information such as your name and email address so we can communicate with
            you about the services
            you’ve registered for. This includes welcome communications and information about accessing,
            using and getting the most from the services.</p>

        <p>
            We will never sell your data. If you are applying for membership we will only pass your details to our 3rd
            party fulfilment
            partner who will process your membership pack and digital assets. To find out more, please view our Data
            Privacy Notice
        </p>

        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <button class="btn btn-success btn-lg btn-block dark-green-bg" id="submit" name="submit" value="first"
                        type="submit">Register and Continue <i class="bi bi-arrow-right"></i></button>
            </div>
        </div>
    </form>
</div>
<br>



