<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<?php $pageTitle = 'Error 404' ?>

<div class="container mb-lg-5">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <div class="gridlayout">
                <div class="gridlayout-editor">
                    <div class="usercontent">
                        <h1>Well, this is awkward.</h1>
                        <p>The page you're looking for doesn't exist.</p>
                        <p><strong>Would you like to try again?</strong></p>
                        <p><a class="btn btn-success"  href="/" title="Home Page">Return to home</a></p>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-6">
            <div class="gridlayout">
                <div class="gridlayout-editor">
                    <div class="usercontent">
                        <p><div class="tenor-gif-embed" data-postid="27637608" data-share-method="host" data-aspect-ratio="1.33333" data-width="100%"><a href="https://tenor.com/view/shocked-gif-27637608">Shocked GIF</a>from <a href="https://tenor.com/search/shocked-gifs">Shocked GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once(base_path('views/partials/footer.phtml')) ?>
