<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>



<section>
    <div class="container-fluid homepage-section1 hide-overflow">
        <div class="ml-5">
            <div class="row" >
                <h1 class="mt-5  text-light">BCS <span class="font-weight-bold">Placement</span></h1>
            </div>
            <div class="row">
                <h1 class="text-light ">Finder</h1>
            </div>
        </div>

        <div class="row homepage-mt-section1"></div>

        <div class="row homepage-bg-section1 align-items-center">

            <div class="col-md-8">
                <h4 class="mt-3  text-light ml-5"><span class="font-weight-bold">Unlock</span> Your Career
                    <span class="font-weight-bold">Potential</span> with
                    <span class="font-weight-bold">BCS</span>:
                </h4>

                <h4 class=" text-light ml-5">Elevate Your <span class="font-weight-bold text-purple">Goals</span>!</h4>
            </div>

            <div class="col-md-3 center">
                <a href='/register' class='btn homepage-button homepage-btn-block mt-3 center' role='button' >GET STARTED <i class="bi bi-arrow-right"></i></a>
            </div>

            <div class="row mt-4"></div>

        </div>
    </div>
</section>


<section>

    <div class="container-fluid homepage-section2 hide-overflow">
        <div class="row no-gutters justify-content-center align-items-center ">
            <div class="col-12 homepage-mt-section2"></div>

            <div class="col-md-7">

                <div class="row no-gutters text-center justify-content-center">
                    <div class="col-12">
                        <h2><span class="homepage-text-green">Build Your Career </span> <span class="homepage-text-red font-weight-bold">Momentum</span></h2>
                    </div>
                    <div class="col-12">
                        <img src="image/homePageImg1.png">
                    </div>
                </div>

            </div>

            <div class="col-md-5">
                <div class="row no-gutters justify-content-center">
                    <div class="card homepage-bg-green" style="width: 25rem;">
                        <div class="card-body homepage-bg-green">
                            <h6 class="card-title text-underline text-center">The Transformative Power of University Work Placements</h6>

                            <p class="card-text text-center text-dark">A university work placement is a game-changer!
                                It's an accelerated course in real-world skills,
                                a direct path to building a stellar career.
                                You'll engage with seasoned professionals,
                                expand your network, and unlock opportunities you never knew existed.
                                Plus, it's a paying gig! Earning while learning not only supports you financially
                                but also boosts your confidence and skill set. It's a firsthand look into your future career,
                                propelling you toward your aspirations with invaluable experience.</p>
                            <a href="/register" class="card-link btn homepage-grey-button homepage-btn-block mt-5">Explore <i class="bi bi-arrow-right"></i></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container-fluid homepage-section3 hide-overflow">
        <div class="row no-gutters  align-items-center">
            <div class="col-12 mt-4"></div>

            <div class="col-md-6 p-4 homepage-bg-transparent-black">
                <img src="image/homePageImg2.png">
            </div>

            <div class="col-md-4">
                <div class="row no-gutters justify-content-center">
                    <div class="card homepage-bg-white" style="width: 25rem;" >
                        <div class="card-body homepage-bg-white">
                            <h6 class="card-title text-underline text-center">Optimize Recruitment: Join Our Platform for Perfect Matches!</h6>

                            <p class="card-text text-center text-dark">Looking to revolutionize your recruitment game? Join our platform and unlock a world of possibilities for your placement programs!
                                By being part of our system, you tap into a goldmine of qualified, eager-to-learn students ready to make an impact in your organization. Say goodbye to the costly, time-consuming hunt
                                for talent—our platform streamlines the process, matching you with the perfect candidates efficiently and effectively. Not only that but being on our platform elevates your company's visibility among the student community,
                                cementing your position as a go-to employer. Join us, expand your talent pool, and let's pave the way for mutually beneficial partnerships that drive success.</p>

                            <a href="/register" class="card-link btn homepage-grey-button homepage-btn-block mt-5">Tap In <i class="bi bi-arrow-right"></i></a>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-1">
            </div>
            <div class="col-md-1">
                <h1 class="text-light vertical-text font-weight-bold d-none d-md-block "><span class="homepage-text-orange">Empower</span> Tommorrow</h1>
            </div>

        </div>
    </div>

</section>