<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 text-center">
            <h1 class="mb-3">Account Successfully updated!</h1>
            <p><a class="btn btn-success"  href="/" title="Home Page">Return to home</a></p>
        </div>
    </div>
</div>

<?php require_once(base_path('views/partials/footer.phtml')) ?>