<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

    <style>
        .img {
            height: 256px;
            object-fit: cover;
        }
    </style>

    <section class="bg-light py-3 py-md-5 py-xl-8">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6">
                    <h2 class="mb-4 display-5 text-center">Our Team</h2>
                    <hr class="w-50 mx-auto mb-5 mb-xl-9 border-dark-subtle">
                </div>
            </div>
        </div>

        <div class="container overflow-hidden">
            <div class="row gy-4 gy-lg-0 gx-xxl-5">

                <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" src="/image/abdul.png" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">abdul</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/ahmed.png" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">ahmad</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/arslan.webp" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">arslan</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/firaas.png" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">firaas</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-centre mt-4">

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 offset-md-0 offset-lg-2">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/muj.webp" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">mujahid</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/sheryar.webp" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">sheryar</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-12 col-md-12 col-lg-3 mt-4 mt-lg-0">
                    <div class="card border-0 border-bottom border-primary shadow-sm overflow-hidden" style="width: fit-content">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img" loading="lazy" src="/image/george.webp" alt="IMG not found 😥">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">george</h4>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<?php require_once(base_path('views/partials/footer.phtml')) ?>