<?php require_once(base_path('views/partials/head.phtml')) ?>
<?php require_once(base_path('views/partials/nav.phtml')) ?>
<?php require_once(base_path('views/partials/header.phtml')) ?>

<div class="container mb-5">

    <form name="update-password" action="/changepassword" method="post">
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="currentPassword">Current Password</label>
                <input type="password" class="form-control" name="currentPassword" id="currentPassword">
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <label class="mb-2" for="newPassword">New Password</label>
                <input type="password" class="form-control" name="newPassword" id="newPassword">
            </div>

            <div class="col-md-6 mb-2">
                <label class="mb-2" for="confirmPassword">Confirm Password</label>
                <input type="password" class="form-control" name="confirmPassword" id="confirmPassword">
            </div>
        </div>

        <div class="row mb-3 justify-content-center">
            <div class="col-md-6 mb-2 text-center">
                <button type="submit" class="btn btn-success btn-lg btn-block dark-green-bg mb-2">Update Password</button>
            </div>
        </div>
    </form>

    <?php if (!empty($errors)): ?>
        <div class="row mb-3">
            <div class="col-md-6 mb-2">
                <div class="alert alert-danger" role="alert">
                    <?php foreach ($errors as $error): ?>
                        <p><?= $error ?></p>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

</div>

<?php require_once(base_path('views/partials/footer.phtml')) ?>
